name: CI Test1
on:
  push:
    paths:
      - 'src/**'
##rel
jobs:
  ci_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Gradle Test
        run: ./gradlew test --no-daemon
